name: Deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub Deployment
        if: failure()
        uses: niklasmerz/github-deployment-action@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: -o gregbrimble -r habichat -c master -e production
      - name: Checkout
        uses: actions/checkout@v1.0.0
        with:
          fetch-depth: 1
      - name: Setup Node
        uses: actions/setup-node@v1.2.0
        with:
          fetch-depth: 1
      - name: Install
        run: npm install
      - name: Deploy
        id: deploy
        run: npm run deploy
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
      - name: Update GitHub Deployment
        if: failure()
        uses: niklasmerz/github-deployment-action@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: -o gregbrimble -r habichat -s failure -u https://habichat.gregbrimble.workers.dev -f
      - name: Update GitHub Deployment
        if: success()
        uses: niklasmerz/github-deployment-action@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: -o gregbrimble -r habichat -s success -u https://habichat.gregbrimble.workers.dev -f
