name: Deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub Deployment
        uses: deliverybot/deployment-status@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v1.0.0
        with:
          fetch-depth: 1
      - name: Setup Node
        uses: actions/setup-node@v1.2.0
        with:
          fetch-depth: 1
      - name: Install
        run: npm install
      - name: Deploy
        id: deploy
        run: npm run deploy
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
      - name: Report Success
        if: success()
        uses: deliverybot/deployment-status@v1
        with:
          state: success
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Report Success
        if: failure()
        uses: deliverybot/deployment-status@v1
        with:
          state: failure
          token: ${{ secrets.GITHUB_TOKEN }}
