name: Test
on: [push]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1.0.0
        with:
          fetch-depth: 1
      - name: Setup Node
        uses: actions/setup-node@v1.2.0
        with:
          fetch-depth: 1
      - name: Install
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test:ci
      # - name: Upload Coverage Report
      #   uses: codecov/codecov-action@v1.0.2
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
